-- Setup and context
USE ROLE ACCOUNTADMIN;
USE SCHEMA SNOWFLAKE.ACCOUNT_USAGE;
USE WAREHOUSE MY_WAREHOUSE_NAME;

--Run this first, the results are used to check Foreign Keys
SHOW IMPORTED KEYS IN ACCOUNT;

SELECT 'Foreign Keys' AS REFERENCE_TYPE, "fk_database_name" as source_db, "fk_schema_name"||'.'||"fk_name" as source_object_name, "pk_database_name" as target_db, "pk_schema_name"||'.'||"pk_table_name" as target_object_name
FROM TABLE(RESULT_SCAN(LAST_QUERY_ID()))
WHERE "fk_database_name" != "pk_database_name"

    UNION ALL
--Check Masking Policies    
SELECT 'Policy Reference' AS REFERENCE_TYPE, POLICY_DB AS SOURCE_DB, POLICY_SCHEMA||'.'||POLICY_NAME AS SOURCE_OBJECT_NAME, REF_DATABASE_NAME AS TARGET_DB, REF_SCHEMA_NAME||'.'||REF_ENTITY_NAME AS TARGET_OBJECT_NAME
FROM POLICY_REFERENCES
WHERE POLICY_DB != REF_DATABASE_NAME

    UNION ALL
--Check Views
SELECT 'View References' AS REFERENCE_TYPE, REFERENCING_DATABASE AS SOURCE_DB, REFERENCING_SCHEMA||'.'||REFERENCING_OBJECT_NAME AS SOURCE_OBJECT_NAME, REFERENCED_DATABASE AS TARGET_DB, REFERENCED_SCHEMA||'.'||REFERENCED_OBJECT_NAME AS TARGET_OBJECT_NAME
FROM OBJECT_DEPENDENCIES
WHERE REFERENCED_DATABASE != REFERENCING_DATABASE

ORDER BY REFERENCE_TYPE;
